### ISSUE TITLE
Rainbow tunnel gif might be too much for people prone to seizures or migraines

### ISSUE THREAD

**Issue by gbob81** [kmh11/chemspeller#22]
While I don't suffer from epilepsy myself, I do suffer from chronic migraines, and from what I understand, the two seem to share many of the same triggers. The chemspell website is awesome (I used it to create a puzzle for a digital scavenger hunt), but I could immediately tell the rainbow tunnel animation was going to be problematic for me. After about 3 seconds of watching it (I was looking for a way to turn it off or send a comment on the site), I now feel a migraine coming on. Just wanted to let you know. I think if the colors were less intense (lower contrast) and the pattern moved slower it would be better, or a different type of animation might be safer.

**Comment by kmh11** [comment]
Oh no, I'm so sorry! I've gone ahead and made the rainbow animation only show up if explicitly requested, and added a warning there. I'll find and replace it with a less intense one soon. Sorry you had to be the victim of 8th grade me's obsession with questionable design... I'm glad the site was useful for you at least!

**Comment by kmh11** [comment]
Oh and it's possible the unmodified script is cached on your browser, so you may want to hard refresh (control-shift-r, or cmd-shift-r on mac) on [https://www.chemspeller.com/chemspell.js](https://www.chemspeller.com/chemspell.js) before visiting again. Or just wait until it gets flushed from the cache, which likely happened already (sorry for the late reply! end of semester busyness 😞)

**Comment by gbob81** [comment]
Thank you, much appreciated! :)
